(function(b,f){jPlayerPlaylist=function(a,c,d){var e=this;this.current=0;this.removing=this.shuffled=this.loop=!1;this.cssSelector=b.extend({},this._cssSelector,a);this.options=b.extend(!0,{keyBindings:{next:{key:221,fn:function(){e.next()}},previous:{key:219,fn:function(){e.previous()}},shuffle:{key:83,fn:function(){e.shuffle()}}},stateClass:{shuffled:"jp-state-shuffled"}},this._options,d);this.playlist=[];this.original=[];this._initPlaylist(c);this.cssSelector.details=this.cssSelector.cssSelectorAncestor+
" .jp-details";this.cssSelector.playlist=" .jp-playlist";this.cssSelector.next=this.cssSelector.cssSelectorAncestor+" .jp-next";this.cssSelector.previous=this.cssSelector.cssSelectorAncestor+" .jp-previous";this.cssSelector.shuffle=this.cssSelector.cssSelectorAncestor+" .jp-shuffle";this.cssSelector.shuffleOff=this.cssSelector.cssSelectorAncestor+" .jp-shuffle-off";this.options.cssSelectorAncestor=this.cssSelector.cssSelectorAncestor;this.options.repeat=function(a){e.loop=a.jPlayer.options.loop};
b(this.cssSelector.jPlayer).bind(b.jPlayer.event.ready,function(){e._init()});b(this.cssSelector.jPlayer).bind(b.jPlayer.event.ended,function(){e.next()});b(this.cssSelector.jPlayer).bind(b.jPlayer.event.play,function(){b(this).jPlayer("pauseOthers")});b(this.cssSelector.jPlayer).bind(b.jPlayer.event.resize,function(a){a.jPlayer.options.fullScreen?b(e.cssSelector.details).show():b(e.cssSelector.details).hide()});b(this.cssSelector.previous).click(function(a){a.preventDefault();e.previous();e.blur(this)});
b(this.cssSelector.next).click(function(a){a.preventDefault();e.next();e.blur(this)});b(this.cssSelector.shuffle).click(function(a){a.preventDefault();e.shuffled&&b(e.cssSelector.jPlayer).jPlayer("option","useStateClassSkin")?e.shuffle(!1):e.shuffle(!0);e.blur(this)});b(this.cssSelector.shuffleOff).click(function(a){a.preventDefault();e.shuffle(!1);e.blur(this)}).hide();this.options.fullScreen||b(this.cssSelector.details).hide();b(this.cssSelector.playlist+" ul").empty();this._createItemHandlers();
b(this.cssSelector.jPlayer).jPlayer(this.options)};jPlayerPlaylist.prototype={_cssSelector:{jPlayer:"#jquery_jplayer_1",cssSelectorAncestor:"#jp_container_1"},_options:{playlistOptions:{autoPlay:!1,loopOnPrevious:!1,shuffleOnLoop:!0,enableRemoveControls:!1,displayTime:"slow",addTime:"fast",removeTime:"fast",shuffleTime:"slow",itemClass:"jp-playlist-item",freeGroupClass:"jp-free-media",freeItemClass:"jp-playlist-item-free",removeItemClass:"jp-playlist-item-remove"}},option:function(a,b){if(b===f)return this.options.playlistOptions[a];
this.options.playlistOptions[a]=b;switch(a){case "enableRemoveControls":this._updateControls();break;case "itemClass":case "freeGroupClass":case "freeItemClass":case "removeItemClass":this._refresh(!0),this._createItemHandlers()}return this},_init:function(){var a=this;this._refresh(function(){a.options.playlistOptions.autoPlay?a.play(a.current):a.select(a.current)})},_initPlaylist:function(a){this.current=0;this.removing=this.shuffled=!1;this.original=b.extend(!0,[],a);this._originalPlaylist()},
_originalPlaylist:function(){var a=this;this.playlist=[];b.each(this.original,function(b){a.playlist[b]=a.original[b]})},_refresh:function(a){var c=this;if(a&&!b.isFunction(a))b(this.cssSelector.playlist+" ul").empty(),b.each(this.playlist,function(a){b(c.cssSelector.playlist+" ul").append(c._createListItem(c.playlist[a]))}),this._updateControls();else{var d=b(this.cssSelector.playlist+" ul").children().length?this.options.playlistOptions.displayTime:0;b(this.cssSelector.playlist+" ul").slideUp(d,
function(){var e=b(this);b(this).empty();b.each(c.playlist,function(a){e.append(c._createListItem(c.playlist[a]))});c._updateControls();b.isFunction(a)&&a();c.playlist.length?b(this).slideDown(c.options.playlistOptions.displayTime):b(this).show()})}},_createListItem:function(a){var c=this,d="<li><div "+(a.index!=f?"class='keeng-album'":"")+" >";if(a.free){var e=!0,d=d+("<span class='"+this.options.playlistOptions.freeGroupClass+"'>(");b.each(a,function(a,f){b.jPlayer.prototype.format[a]&&(e?e=!1:
d+=" | ",d+="<a class='"+c.options.playlistOptions.freeItemClass+"' href='"+f+"' tabindex='-1'>"+a+"</a>")});d+=")</span>"}d=a.index!=f?d+('<div class="ka-content" ><a href="javascript:;" tabindex="0" title="'+a.title+'" class="ka-lnk '+this.options.playlistOptions.itemClass+'" style=""><span class="number-no">'+a.index+'</span></a><div class="ka-info"><h3 class="ka-info-h3"><a class="jp-playlist-item-h3" href="javascript:;" title="'+a.title+'">'+a.title+'</a></h3><p class="ka-info-singer"><a name="bxh_singer_name">'+
a.artist+'</a><div class="icon_sv"><a class="i_dl" href="#"><i class="icon_main"></i></a><a class="i_rb" href="#"><i class="icon_main"></i></a><a class="i_gift" href="#"><i class="icon_main"></i></a></div><div class="icon_view"><span><i class="icon_main"></i>328</span><span><i class="icon_main"></i>2k</span></div><span name="bxh_listen" >'+a.listen_no+"</span></span></p>"):d+('<div tabindex="0" class="ka-content audio-content '+this.options.playlistOptions.itemClass+'"><a title="'+a.title+'" class="ka-lnk"></a><div class="ka-info"><h3 class="ka-info-h3"><a title="'+a.title+'" class="jp-playlist-item-h3" onclick="load_tones('+a.id+');" href="#">'+a.title+'</a></h3><p class="ka-info-singer"><a>'+a.artist+
'</a></span></p><div class="icon_sv"><a class="i_dl" href="##"><i class="icon_main"></i></a><a class="i_rb" href="#"><i class="icon_main"></i></a><a class="i_gift" href="##"><i class="icon_main"></i></a></div><div class="icon_view"><span><i class="icon_main"></i>328</span><span><i class="icon_main"></i>2k</span></div></div></div>');return d+="</div></li>"},_createItemHandlers:function(){var a=this;b(this.cssSelector.playlist).off("click","a."+this.options.playlistOptions.itemClass).on("click","a."+this.options.playlistOptions.itemClass,
function(c){c.preventDefault();c=b(this).parent().parent().parent().index();a.current!==c?a.play(c):b(a.cssSelector.jPlayer).jPlayer("play");a.blur(this)});b(this.cssSelector.playlist).off("click","a.jp-playlist-item-h3").on("click","a.jp-playlist-item-h3",function(c){c.preventDefault();c=b(this).parent().parent().parent().parent().parent().index();0<b(".lyric-audio").length&&b("#lyric").html(b(b(".lyric-audio")[c]).html());a.current!==c?a.play(c):b(a.cssSelector.jPlayer).jPlayer("play");a.blur(this)});
b(this.cssSelector.playlist).off("click","a."+this.options.playlistOptions.freeItemClass).on("click","a."+this.options.playlistOptions.freeItemClass,function(c){c.preventDefault();b(this).parent().parent().find("."+a.options.playlistOptions.itemClass).click();a.blur(this)});b(this.cssSelector.playlist).off("click","a."+this.options.playlistOptions.removeItemClass).on("click","a."+this.options.playlistOptions.removeItemClass,function(c){c.preventDefault();c=b(this).parent().parent().index();a.remove(c);
a.blur(this)})},_updateControls:function(){this.options.playlistOptions.enableRemoveControls?b(this.cssSelector.playlist+" ."+this.options.playlistOptions.removeItemClass).show():b(this.cssSelector.playlist+" ."+this.options.playlistOptions.removeItemClass).hide();this.shuffled?b(this.cssSelector.jPlayer).jPlayer("addStateClass","shuffled"):b(this.cssSelector.jPlayer).jPlayer("removeStateClass","shuffled");b(this.cssSelector.shuffle).length&&b(this.cssSelector.shuffleOff).length&&(this.shuffled?(b(this.cssSelector.shuffleOff).show(),
b(this.cssSelector.shuffle).hide()):(b(this.cssSelector.shuffleOff).hide(),b(this.cssSelector.shuffle).show()))},_highlight:function(a){this.playlist.length&&a!==f&&(b(this.cssSelector.playlist+" .jp-playlist-current").removeClass("jp-playlist-current"),b(this.cssSelector.playlist+" li:nth-child("+(a+1)+")").addClass("jp-playlist-current").find(".jp-playlist-item").addClass("jp-playlist-current"),b(".ava_song").html('<h1 class="info-player-h1"><span id="song_name" class="info-player-name">'+
this.playlist[a].title+'</span> - <a id="song_singer_name" class="info-player-singer">'+this.playlist[a].artist+'</a></h1><p class="info-player-p"><span class="show_web">S\u00e1ng t\u00e1c: <span id="author">'+this.playlist[a].author+'</span> | Th\u1ec3 lo\u1ea1i: <span id="song_cat">'+this.playlist[a].category+'</span> |  </span> L\u01b0\u1ee3t nghe: <span id="song_listen_no">'+this.playlist[a].listen_no+'</span> | L\u01b0\u1ee3t t\u1ea3i: <span id="song_download_no">'+this.playlist[a].download_no+
"</span>\t</p>"))},setPlaylist:function(a){this._initPlaylist(a);this._init()},add:function(a,c){b(this.cssSelector.playlist+" ul").append(this._createListItem(a)).find("li:last-child").hide().slideDown(this.options.playlistOptions.addTime);this._updateControls();this.original.push(a);this.playlist.push(a);c?this.play(this.playlist.length-1):1===this.original.length&&this.select(0)},remove:function(a){var c=this;if(a===f)return this._initPlaylist([]),this._refresh(function(){b(c.cssSelector.jPlayer).jPlayer("clearMedia")}),
!0;if(this.removing)return!1;a=0>a?c.original.length+a:a;0<=a&&a<this.playlist.length&&(this.removing=!0,b(this.cssSelector.playlist+" li:nth-child("+(a+1)+")").slideUp(this.options.playlistOptions.removeTime,function(){b(this).remove();if(c.shuffled){var d=c.playlist[a];b.each(c.original,function(a){if(c.original[a]===d)return c.original.splice(a,1),!1})}else c.original.splice(a,1);c.playlist.splice(a,1);c.original.length?a===c.current?(c.current=a<c.original.length?c.current:c.original.length-1,
c.select(c.current)):a<c.current&&c.current--:(b(c.cssSelector.jPlayer).jPlayer("clearMedia"),c.current=0,c.shuffled=!1,c._updateControls());c.removing=!1}));return!0},select:function(a){a=0>a?this.original.length+a:a;0<=a&&a<this.playlist.length?(this.current=a,this._highlight(a),b(this.cssSelector.jPlayer).jPlayer("setMedia",this.playlist[this.current])):this.current=0},play:function(a){a=0>a?this.original.length+a:a;0<=a&&a<this.playlist.length?this.playlist.length&&(this.select(a),b(this.cssSelector.jPlayer).jPlayer("play"),
0<b("#jscroll-bxh").length&&b("#jscroll-bxh").data("jsp").scrollToY(92*a),0<b("#jscroll-album").length&&0!=a&&b("#jscroll-album").data("jsp").scrollToY(50*a),0<b(".lyric-audio").length&&b("#lyric").html(b(b(".lyric-audio")[a]).html())):a===f&&b(this.cssSelector.jPlayer).jPlayer("play")},pause:function(){b(this.cssSelector.jPlayer).jPlayer("pause")},next:function(){var a=this.current+1<this.playlist.length?this.current+1:0;this.loop?0===a&&this.shuffled&&this.options.playlistOptions.shuffleOnLoop&&
1<this.playlist.length?this.shuffle(!0,!0):this.play(a):0<a&&this.play(a)},previous:function(){var a=0<=this.current-1?this.current-1:this.playlist.length-1;(this.loop&&this.options.playlistOptions.loopOnPrevious||a<this.playlist.length-1)&&this.play(a)},shuffle:function(a,c){var d=this;a===f&&(a=!this.shuffled);(a||a!==this.shuffled)&&b(this.cssSelector.playlist+" ul").slideUp(this.options.playlistOptions.shuffleTime,function(){(d.shuffled=a)?d.playlist.sort(function(){return.5-Math.random()}):d._originalPlaylist();
d._refresh(!0);c||!b(d.cssSelector.jPlayer).data("jPlayer").status.paused?d.play(0):d.select(0);b(this).slideDown(d.options.playlistOptions.shuffleTime)})},blur:function(a){b(this.cssSelector.jPlayer).jPlayer("option","autoBlur")&&b(a).blur()}}})(jQuery);function loadContent(){jQuery("#jscroll-bxh").jScrollPane();jQuery("#jscroll-bxh").data("jsp").reinitialise();var b=getParameterByName("st");void 0==b|null==b&&(b=0);0==b&&jplayerList.play(0);for(i=0;i<b;i++)jplayerList.next()}
function loadContentAlbum(){jQuery("#jscroll-album").jScrollPane();jQuery("#jscroll-album").data("jsp").reinitialise()};
